import os
os.environ['HUGGINGFACE_HUB_CACHE'] = 'cache'

from speechbrain.pretrained import EncoderDecoderASR
from pydub import AudioSegment

asr_model = EncoderDecoderASR.from_hparams(source="speechbrain/asr-crdnn-rnnlm-librispeech", savedir="./pretrained_models/ASR")

def ASR(file, timestamps):
    audio = AudioSegment.from_file(file)
    
    result = []
    count = 0
    for timestamp in timestamps:
        # Extract parameter from array
        start = timestamp[0]
        end = timestamp[1]

        # Extract the audio segment for ASR
        segment = audio[start * 1000 : end * 1000]
        output_path = "temp/segments/result_{}-{}.wav".format(start, end)
        segment.export(output_path, format="wav")

        asr_output = asr_model.transcribe_file(output_path)
        result.append([asr_output, count])

        # To remove the file generated by ASR
        for item in os.listdir("."):
            if item.endswith(".wav"):
                os.remove(item)

        count += 1
    return result